{
	"name": "ContextSensitive",
	"version": "1.0.16",
	"icon": "fab fa-battle-net",
	"category": "undefined",
	"author": "ProjectAlice",
	"maintainers": [
		"Psycho",
		"maxbachmann"
	],
	"desc": "ContextSensitive is the official context sensitive skill. It handle intents like 'Delete this', 'Forget about that'",
	"aliceMinVersion": "1.0.0-a6",
	"systemRequirements": [],
	"pipRequirements": [],
	"conditions": {
		"lang": [
			"en",
			"fr",
			"de",
			"it"
		]
	}
}
